### ISSUE TITLE
remove line

### ISSUE THREAD

**Issue by sainiaj** [funsocietyirc/MMM-Wunderlist-Enhanced#4]
is their a way to remove the horizontal lines 
and just show the text

**Comment by davericher** [comment]
just the Horizontal line, or the whole header?

**Comment by sainiaj** [comment]
Both the header as well as horizontal line

**Comment by davericher** [comment]
Would you keep a separation of lists or would u want them all mingled together

**Comment by sainiaj** [comment]
All together I only use one list "inbox"

On Jun 23, 2017 12:02 AM, "Dave Richer" <notifications@github.com> wrote:

Would you keep a separation of lists or would u want them all mingled
together

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/funsocietyirc/MMM-Wunderlist-Enhanced/issues/4#issuecomment-310565451>,
or mute the thread

**Comment by davericher** [comment]
The mmm-wunderlist package is probably what you are looking for. This one was based on that, it was written for a single list

**Comment by sainiaj** [comment]
Das Luxury has sent you a message via Indiegogo about the Gold Dice for a Rich Lifestyle campaign.

Hi there,

I&#39;m reaching out to ask for your support for my campaign: &quot;Gold Dice for a Rich Lifestyle.&quot;

There are two ways to help:
1. Contribute - even small contributions raise our popularity and give us more visibility on the site.
2. Post to Facebook - in the end, the more people hear about us, the more likely we are to meet our target.

Thank you!

Das Luxury


Help the "Gold Dice for a Rich Lifestyle" campaign reach its goal today!
